language: php

php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'


cache:
  directories:
    - $HOME/.composer/cache

install: composer install --no-interaction

script:
  - composer cs-check
  - composer test